name        : gnome-chess
version     : 3.16.2
release     : 7
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-chess/3.16/gnome-chess-3.16.2.tar.xz : 8f73b4c645a86e775d092b5b334c70d0868953c1a26cac9d5a234e5f83db3b48
license     :
    - GPLv2+
summary     : GNOME Chess Game
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(glu)
    - itstool
description : |
    Play chess in either 3D or 2D, against the computer or a friend
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
