name       : gnome-chess
version    : 3.24.1
release    : 14
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-chess/3.24/gnome-chess-3.24.1.tar.xz : 6c9647beb7579b0a8de4e73698d931b1d9ac2efab4e7d3649f482d2c68ebf8a3
license    : GPL-2.0
component  : games.strategy
summary    : GNOME Chess Game
description: |
    Play chess in either 3D or 2D, against the computer or a friend
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
rundeps    :
    - gnuchess
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
