name       : gnome-chess
version    : 3.28.1
release    : 16
source     :
    - https://download.gnome.org/sources/gnome-chess/3.28/gnome-chess-3.28.1.tar.xz : 61d7eda645ab74fcf6fa586bc3edc49f01d4a4076f98e1e53d4b4c842b600fe1
license    : GPL-2.0-or-later
component  : games.strategy
summary    : GNOME Chess Game
description: |
    Play chess in either 3D or 2D, against the computer or a friend
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
rundeps    :
    - gnuchess
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
