name       : gnome-chess
version    : '42.1'
release    : 28
source     :
    - https://download.gnome.org/sources/gnome-chess/42/gnome-chess-42.1.tar.xz : 66290bf72864cbc6ee7cce8c9f40de8124e8e6097bd76862f2d7aab0c4bdb02c
homepage   : https://wiki.gnome.org/Apps/Chess
license    : GPL-2.0-or-later
component  : games.strategy
summary    : GNOME Chess Game
description: |
    GNOME Chess is a 2D chess game, where games can be played between a combination of human and computer players. GNOME Chess detects known third party chess engines for computer players.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libadwaita-1)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
rundeps    :
    - gnuchess
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
