name       : gnome-chess
version    : 3.18.0
release    : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-chess/3.18/gnome-chess-3.18.0.tar.xz : c841198935d807618c3cecbf10ed24643390d504e17961717bac455f4e1b37ad
license    : GPL-2.0
component  : games.strategy
summary    : GNOME Chess Game
description: |
    Play chess in either 3D or 2D, against the computer or a friend
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
