name       : gnome-chess
version    : '43.1'
release    : 31
source     :
    - https://download.gnome.org/sources/gnome-chess/43/gnome-chess-43.1.tar.xz : 734f092d95fc60409eeaca3427b5a48cb9b599da11995119d85baa99653e0292
homepage   : https://wiki.gnome.org/Apps/Chess
license    : GPL-2.0-or-later
component  : games.strategy
summary    : GNOME Chess Game
description: |
    GNOME Chess is a 2D chess game, where games can be played between a combination of human and computer players. GNOME Chess detects known third party chess engines for computer players.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libadwaita-1)
    - pkgconfig(librsvg-2.0)
    - desktop-file-utils
    - itstool
    - vala
rundeps    :
    - gnuchess
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
