name       : gnome-chess
version    : 3.22.2
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-chess/3.22/gnome-chess-3.22.2.tar.xz : dffdf7f5c5f4ea6bba7ff88b457a75ee5e4c5d9d522d27e1ea4a3d4bb3927792
license    : GPL-2.0
component  : games.strategy
summary    : GNOME Chess Game
description: |
    Play chess in either 3D or 2D, against the computer or a friend
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - itstool
rundeps    :
    - gnuchess
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
