name        : gnome-chess
version     : 3.18.0
release     : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-chess/3.18/gnome-chess-3.18.0.tar.xz : c841198935d807618c3cecbf10ed24643390d504e17961717bac455f4e1b37ad
license     :
    - GPLv2+
summary     : GNOME Chess Game
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(glu)
    - itstool
description : |
    Play chess in either 3D or 2D, against the computer or a friend
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
