name       : gnome-chess
version    : '41.1'
release    : 27
source     :
    - https://download.gnome.org/sources/gnome-chess/41/gnome-chess-41.1.tar.xz : eb619886596396b4033a3f28a3c2e3004b54ebe1b38b40d6422c17b9f2cc17d0
license    : GPL-2.0-or-later
component  : games.strategy
summary    : GNOME Chess Game
description: |
    Play chess in either 3D or 2D, against the computer or a friend
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(gtk4)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
rundeps    :
    - gnuchess
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
